export const NAME_TO_ISO2: Record<string, string> = {
  // Europe
  Albania: "AL",
  Andorra: "AD",
  Armenia: "AM",
  Austria: "AT",
  Azerbaijan: "AZ",
  Belarus: "BY",
  Belgium: "BE",
  Bosnia: "BA",
  "Bosnia and Herzegovina": "BA",
  "Bosnia and Herz.": "BA",
  Bulgaria: "BG",
  Croatia: "HR",
  Cyprus: "CY",
  "Czech Republic": "CZ",
  "Czech Rep.": "CZ",
  Czechia: "CZ",
  Denmark: "DK",
  Estonia: "EE",
  Finland: "FI",
  France: "FR",
  Georgia: "GE",
  Germany: "DE",
  Greece: "GR",
  Hungary: "HU",
  Iceland: "IS",
  Ireland: "IE",
  Italy: "IT",
  Kazakhstan: "KZ",
  Kosovo: "XK",
  Latvia: "LV",
  Liechtenstein: "LI",
  Lithuania: "LT",
  Luxembourg: "LU",
  Malta: "MT",
  Moldova: "MD",
  Monaco: "MC",
  Montenegro: "ME",
  Netherlands: "NL",
  "North Macedonia": "MK",
  Macedonia: "MK",
  Norway: "NO",
  Poland: "PL",
  Portugal: "PT",
  Romania: "RO",
  Russia: "RU",
  "San Marino": "SM",
  Serbia: "RS",
  Slovakia: "SK",
  Slovenia: "SI",
  Spain: "ES",
  Sweden: "SE",
  Switzerland: "CH",
  Turkey: "TR",
  Türkiye: "TR",
  Ukraine: "UA",
  "United Kingdom": "GB",
  UK: "GB",
  England: "GB",
  Scotland: "GB",
  Wales: "GB",
  "Northern Ireland": "GB",
  "Vatican City": "VA",
  "Holy See": "VA",

  // North America
  Canada: "CA",
  Mexico: "MX",
  "United States": "US",
  "United States of America": "US",
  USA: "US",
  "Antigua and Barbuda": "AG",
  Bahamas: "BS",
  Barbados: "BB",
  Belize: "BZ",
  Cuba: "CU",
  Dominica: "DM",
  "Dominican Republic": "DO",
  Grenada: "GD",
  Guatemala: "GT",
  Haiti: "HT",
  Honduras: "HN",
  Jamaica: "JM",
  Nicaragua: "NI",
  Panama: "PA",
  "Saint Kitts and Nevis": "KN",
  "Saint Lucia": "LC",
  "Saint Vincent and the Grenadines": "VC",
  "Trinidad and Tobago": "TT",

  // South America
  Argentina: "AR",
  Bolivia: "BO",
  Brazil: "BR",
  Chile: "CL",
  Colombia: "CO",
  Ecuador: "EC",
  Guyana: "GY",
  Paraguay: "PY",
  Peru: "PE",
  Suriname: "SR",
  Uruguay: "UY",
  Venezuela: "VE",

  // Africa
  Algeria: "DZ",
  Angola: "AO",
  Benin: "BJ",
  Botswana: "BW",
  "Burkina Faso": "BF",
  Burundi: "BI",
  "Cabo Verde": "CV",
  "Cape Verde": "CV",
  Cameroon: "CM",
  "Central African Republic": "CF",
  Chad: "TD",
  Comoros: "KM",
  Congo: "CG",
  "Republic of the Congo": "CG",
  "Democratic Republic of the Congo": "CD",
  DRC: "CD",
  "Cote d'Ivoire": "CI",
  "Côte d’Ivoire": "CI",
  "Ivory Coast": "CI",
  Djibouti: "DJ",
  Egypt: "EG",
  "Equatorial Guinea": "GQ",
  Eritrea: "ER",
  Eswatini: "SZ",
  Swaziland: "SZ",
  Ethiopia: "ET",
  Gabon: "GA",
  Gambia: "GM",
  Ghana: "GH",
  Guinea: "GN",
  "Guinea-Bissau": "GW",
  Kenya: "KE",
  Lesotho: "LS",
  Liberia: "LR",
  Libya: "LY",
  Madagascar: "MG",
  Malawi: "MW",
  Mali: "ML",
  Mauritania: "MR",
  Mauritius: "MU",
  Morocco: "MA",
  Mozambique: "MZ",
  Namibia: "NA",
  Niger: "NE",
  Nigeria: "NG",
  Rwanda: "RW",
  "Sao Tome and Principe": "ST",
  "São Tomé and Príncipe": "ST",
  Senegal: "SN",
  Seychelles: "SC",
  "Sierra Leone": "SL",
  Somalia: "SO",
  "South Africa": "ZA",
  "South Sudan": "SS",
  Sudan: "SD",
  Tanzania: "TZ",
  Togo: "TG",
  Tunisia: "TN",
  Uganda: "UG",
  Zambia: "ZM",
  Zimbabwe: "ZW",

  // Asia
  Afghanistan: "AF",
  Bahrain: "BH",
  Bangladesh: "BD",
  Bhutan: "BT",
  Brunei: "BN",
  Cambodia: "KH",
  China: "CN",
  "Hong Kong": "HK",
  Macao: "MO",
  Macau: "MO",
  Taiwan: "TW",
  "Taiwan, Province of China": "TW",
  India: "IN",
  Indonesia: "ID",
  Iran: "IR",
  "Iran, Islamic Republic of": "IR",
  Iraq: "IQ",
  Israel: "IL",
  Japan: "JP",
  Jordan: "JO",
  Kuwait: "KW",
  Kyrgyzstan: "KG",
  Lao: "LA",
  Laos: "LA",
  "Lao People's Democratic Republic": "LA",
  Lebanon: "LB",
  Malaysia: "MY",
  Maldives: "MV",
  Mongolia: "MN",
  Myanmar: "MM",
  Burma: "MM",
  Nepal: "NP",
  "North Korea": "KP",
  "Korea, Democratic People's Republic of": "KP",
  "South Korea": "KR",
  "Korea, Republic of": "KR",
  Oman: "OM",
  Pakistan: "PK",
  Palestine: "PS",
  "State of Palestine": "PS",
  Philippines: "PH",
  Qatar: "QA",
  "Saudi Arabia": "SA",
  Singapore: "SG",
  "Sri Lanka": "LK",
  Syria: "SY",
  "Syrian Arab Republic": "SY",
  Tajikistan: "TJ",
  Thailand: "TH",
  "Timor-Leste": "TL",
  "East Timor": "TL",
  Turkmenistan: "TM",
  "United Arab Emirates": "AE",
  Uzbekistan: "UZ",
  Vietnam: "VN",
  Yemen: "YE",

  // Oceania
  Australia: "AU",
  Fiji: "FJ",
  Kiribati: "KI",
  "Marshall Islands": "MH",
  Micronesia: "FM",
  "Federated States of Micronesia": "FM",
  Nauru: "NR",
  "New Zealand": "NZ",
  Palau: "PW",
  "Papua New Guinea": "PG",
  Samoa: "WS",
  "Solomon Islands": "SB",
  Tonga: "TO",
  Tuvalu: "TV",
  Vanuatu: "VU",

  // Caribbean/Oceania extras (already included where applicable)

  // Special cases / aliases often seen in datasets
  "Russian Federation": "RU",
  "Moldova, Republic of": "MD",
  "Bolivia (Plurinational State of)": "BO",
  "Venezuela (Bolivarian Republic of)": "VE",
  "Tanzania, United Republic of": "TZ",
  "United Kingdom of Great Britain and Northern Ireland": "GB",
  "United States Minor Outlying Islands": "UM",
  "Congo, Democratic Republic of the": "CD",
  "Congo, Republic of the": "CG",
  "Korea (Democratic People's Republic of)": "KP",
  "Korea (Republic of)": "KR",
  "Micronesia (Federated States of)": "FM",
  "The Gambia": "GM",
};
